//
// Created by Maria Baburina on 2018-07-26.
//

#ifndef VCSCHECKOUTTESTIDEAFILESCMAKELISTS_SOURCE_H
#define VCSCHECKOUTTESTIDEAFILESCMAKELISTS_SOURCE_H


class source {

};


#endif //VCSCHECKOUTTESTIDEAFILESCMAKELISTS_SOURCE_H
